on:
  issues:
    types: [opened, edited]

jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
#      - name: Add assigness
 #       uses: actions-cool/issues-helper@v3
  #      with:
   #       actions: 'add-assignees'
    #      token: ${{ secrets.GITHUB_TOKEN }}
     #     issue-number: ${{ github.event.issue.number }}
      #    assignees: 'xxx' or 'xx1,xx2'
       #   random-to: 1
      - name: Get Issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'get-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: cloudflare-kv-action
        uses: zentered/cloudflare-kv-action@v1.0.0
        id: cloudflare_kv
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          namespace_identifier: '123'
          key_name: 'hello'
          value: 'world'
          expiration_ttl: 120
      - name: Value
        run: echo "${{ steps.cloudflare_kv.outputs.value }}"
